# Numpy Alıştırmaları

### 1'den 10'a kadar bir Numpy dizisi oluşturun

In [2]:
import numpy as np

In [3]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2 boyutlu bir Numpy dizisi oluşturun

In [5]:
x = np.random.randint(1,10,(2,2))
x

array([[2, 2],
       [9, 3]])

In [6]:
x.ndim

2

## Boyutları 2x3 olan bir Numpy dizisinin satır sayısını bulun

In [10]:
x = np.random.randint(1,10,(2,3))
x

array([[3, 6, 5],
       [3, 1, 9]])

In [11]:
x.shape[0]

2

## Boyutları 2x3 olan bir Numpy dizisinin sütun sayısını bulun

In [12]:
x.shape[1]

3

## Bir Numpy dizisindeki en büyük değeri bulun

In [16]:
x.max()

8

## Bir Numpy dizisindeki en küçük değeri bulun

In [17]:
x.min()

2

## Bir Numpy dizisindeki ortalamayı bulun

In [19]:
x.mean()

5.333333333333333

## Bir Numpy dizisindeki standart sapmayı bulun

In [20]:
x.std()

2.2110831935702664

## Bir Numpy dizisinde tekrar eden elemanları bulun

In [15]:
numpy_array = np.array([1,1,1,2,2,3,3,3,4,5,6,7,7,3,6,7,8,9,10,12,13])

repetative_values = []

for i in numpy_array:
    for r in numpy_array:
        if numpy_array[i] == numpy_array[r]:
            if numpy_array[r] in repetative_values:
                continue
            else:
                repetative_values.append(numpy_array[r])

repetative_values = np.array(repetative_values)

In [16]:
repetative_values

array([1, 2, 3, 4, 5, 6, 7])

## 2 boyutlu bir Numpy dizisindeki tüm elemanların toplamını bulun

In [26]:
a = np.random.randint(1,20,(3,3))
a.ndim

2

In [28]:
a.sum()

85

## 2 boyutlu bir Numpy dizisindeki her bir sütundaki elemanların toplamını bulun

In [46]:
a

array([[ 2, 11, 19],
       [ 7,  9, 15],
       [ 2,  5, 15]])

In [47]:
a.sum(axis=0)

array([11, 25, 49])

## Numpy dizisi boyutlarını değiştirin

In [31]:
a.reshape(1,9)

array([[ 2, 19, 11,  9,  7, 15, 15,  5,  2]])

In [33]:
a.reshape(9,1)

array([[ 2],
       [19],
       [11],
       [ 9],
       [ 7],
       [15],
       [15],
       [ 5],
       [ 2]])

## Numpy dizisindeki elemanların transpozunu alın

In [34]:
a.transpose()

array([[ 2,  9, 15],
       [19,  7,  5],
       [11, 15,  2]])

## Numpy dizisindeki elemanların sıralamasını yapın

In [42]:
a.sort()
a

array([[ 2, 11, 19],
       [ 7,  9, 15],
       [ 2,  5, 15]])

## 2 boyutlu bir Numpy dizisindeki her bir sütundaki elemanların ortalamasını bulun

In [49]:
a.mean(axis=0)

array([ 3.66666667,  8.33333333, 16.33333333])

## 2 boyutlu bir Numpy dizisindeki her bir satırdaki elemanların standart sapmasını bulun

In [48]:
a.std(axis=1)

array([6.94422222, 3.39934634, 5.55777733])

## 2 boyutlu bir Numpy dizisinde belirli bir elemanın index değerini bulun

In [74]:
np.where(a == 2)

(array([0, 2], dtype=int64), array([0, 0], dtype=int64))

## 2 boyutlu bir Numpy dizisinde belirli bir sütunu seçin

In [67]:
a

array([[ 2, 11, 19],
       [ 7,  9, 15],
       [ 2,  5, 15]])

In [69]:
a[:,1:2]

array([[11],
       [ 9],
       [ 5]])

## 2 boyutlu bir Numpy dizisinde belirli bir satırı seçin

In [70]:
a[:1,:]

array([[ 2, 11, 19]])